import { Toaster } from "@/components/ui/sonner";
import SessionProvider from "@/provider/SessionProvider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <body>{children}</body>
        <Toaster richColors duration={5000} />
      </SessionProvider>
    </html>
  );
}
